---
title: "Bayesian Statistics: Movie Popularity Data Analysis"
output: 
  html_document: 
    fig_height: 4
    fig_width: 9
    highlight: pygments
    theme: yeti
    toc: yes
    keep_md: yes
---
## Setup
```{r set_defaults, message=FALSE}
# set defaults: cache chunks to speed compiling subsequent edits.
knitr::opts_chunk$set(cache=TRUE, echo = TRUE)
```

### Load packages

```{r load-packages, message = FALSE}
library(ggplot2)
library(dplyr)
library(statsr)
library(BAS)
library(ggthemes)
library(plotly)
library(kableExtra)
```

### Load data


```{r load-data}
load("movies.Rdata")
```



* * *

## Part 1: Data


* * *

## Part 2: Data manipulation

```{r create_new_vars}
movies2 <- movies %>%
    mutate(feature_film = factor(title_type == 'Feature Film', labels=c("No", "Yes"))) %>%
    mutate(drama  = factor(genre == 'Drama', labels=c("No", "Yes"))) %>%
    mutate(mpaa_rating_R = factor(mpaa_rating == 'R', labels=c("No", "Yes"))) %>%
    mutate(oscar_season = factor(thtr_rel_month %in% 10:12, labels=c("No", "Yes"))) %>%
    mutate(summer_season = factor(thtr_rel_month %in% 5:8, labels=c("No", "Yes"))) 
sample_n(movies2, 10) %>%
    select(title, feature_film:summer_season) %>%
    kbl() %>% 
    kable_styling(bootstrap_options = c("condensed"))

```


* * *

## Part 3: Exploratory data analysis



* * *

## Part 4: Modeling



* * *

## Part 5: Prediction



* * *

## Part 6: Conclusion

